### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by mrbenhowl** [mrbenhowl/using-react-usecontext-hook-with-dynamic-values-example#1]
- [x] Complete draft Medium post
- [x] Get it reviewed
- [x] Include reference to Medium post
- [x] Add instructions for starting project locally - could do for other project as well.

**Comment by mrbenhowl** [comment]
Yay. All done. Good work ;)
